In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv('ecommerce_raw.csv')

print(df.head)

In [29]:
#Statistics
df.nunique()

Order_ID            8000
Order_Date           365
Customer_ID          454
Product               10
Category               7
Price               6861
Quantity               4
Country                7
Payment_Method         4
Discount_Percent       4
dtype: int64

In [30]:
#Checking the NaN values
df.isnull().sum()

Order_ID               0
Order_Date            30
Customer_ID            0
Product                0
Category               0
Price                 37
Quantity              35
Country                0
Payment_Method      1672
Discount_Percent    1203
dtype: int64

In [31]:
#Duplicates
df.duplicated().sum()

np.int64(18)

In [32]:
#Checking NaN in Discount_Price
df[df['Discount_Percent'].isnull()]

,Order_ID,Order_Date,Customer_ID,Product,Category,Price,Quantity,Country,Payment_Method,Discount_Percent
9,ORD001733,2024-10-07,CUST01070,Phone Stand,Accessories,99999.00,2.0,Poland,PayPal,NaN
14,ORD000683,2024-07-04,CUST01001,Monitor,Displays,479.92,3.0,Germany,NaN,NaN
29,ORD002305,2024-12-28,CUST01151,Webcam,Video,40.30,1.0,France,Credit Card,NaN
32,ORD002866,2024-06-22,CUST01003,Mouse,Peripherals,64.00,4.0,USA,Debit Card,NaN
57,ORD001617,2024-03-14,CUST01001,Keyboard,Peripherals,73.66,2.0,Germany,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7963,ORD006976,2024-04-20,CUST01001,Monitor,Displays,532.95,4.0,Poland,Credit Card,NaN
7971,ORD000190,2024-10-11,CUST01001,Mouse,Peripherals,77.95,1.0,France,Bank Transfer,NaN
7983,ORD004844,2024-05-05,CUST01001,Headphones,Audio,169.96,3.0,France,NaN,NaN
7996,ORD002392,2024-01-27,CUST01001,Mouse,Peripherals,86.54,4.0,UK,Credit Card,NaN
8007,ORD004427,2024-05-07,CUST01001,Desk Lamp,Accessories,111.93,4.0,USA,Bank Transfer,NaN

In [33]:
#Checking if value 0 is present in dataset
df[df['Discount_Percent'] == 0]

,Order_ID,Order_Date,Customer_ID,Product,Category,Price,Quantity,Country,Payment_Method,Discount_Percent
0,ORD001222,2024-03-24,CUST01001,Monitor,Displays,508.44,2.0,USA,NaN,0.0
2,ORD002139,2024-06-29,CUST01003,Webcam,Video,122.58,3.0,Poland,Credit Card,0.0
3,ORD003371,2024-05-14,CUST01001,Headphones,Audio,95.80,2.0,UK,Credit Card,0.0
4,ORD006903,2024-03-14,CUST01062,Desk Lamp,Accessories,42.77,3.0,France,NaN,0.0
6,ORD001278,2024-05-07,CUST01011,USB Hub,Peripherals,30.18,3.0,Germany,Credit Card,0.0
...,...,...,...,...,...,...,...,...,...,...
8009,ORD000467,2024-01-27,CUST01002,Desk Lamp,Accessories,78.92,2.0,Canada,Credit Card,0.0
8010,ORD006266,2024-08-26,CUST01001,Laptop,Computers,1075.66,2.0,UK,Bank Transfer,0.0
8014,ORD005192,2024-12-24,CUST01004,Mouse,Peripherals,0.00,3.0,Germany,Bank Transfer,0.0
8015,ORD005227,2024-09-09,CUST01001,Mouse,Peripherals,93.60,4.0,France,Bank Transfer,0.0
8018,ORD007604,2024-05-24,CUST01002,Webcam,Video,59.86,3.0,USA,Credit Card,0.0

In [34]:
#NaN values in Dicount_Precent column are prboably values missing from DataSet

In [35]:
#Checking Payment_Method column

df[df['Payment_Method'].isnull()]

,Order_ID,Order_Date,Customer_ID,Product,Category,Price,Quantity,Country,Payment_Method,Discount_Percent
0,ORD001222,2024-03-24,CUST01001,Monitor,Displays,508.44,2.0,USA,NaN,0.0
4,ORD006903,2024-03-14,CUST01062,Desk Lamp,Accessories,42.77,3.0,France,NaN,0.0
10,ORD006557,2024-09-11,CUST01261,Desk Lamp,Accessories,48.51,2.0,Canada,NaN,0.0
13,ORD005610,2024-03-11,CUST01008,Headphones,Audio,0.00,2.0,France,NaN,0.0
14,ORD000683,2024-07-04,CUST01001,Monitor,Displays,479.92,3.0,Germany,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7994,ORD007582,2024-11-02,CUST01002,Keyboard,Peripherals,105.02,4.0,Canada,NaN,0.0
7995,ORD005612,2024-11-28,CUST01001,USB Hub,Peripherals,99999.00,1.0,USA,NaN,10.0
8006,ORD005579,2024-12-04,CUST01001,Laptop,Computers,1104.23,1.0,Canada,NaN,15.0
8008,ORD005335,2024-12-16,CUST01001,Desk Lamp,Accessories,73.95,3.0,Netherlands,NaN,0.0
8013,ORD003773,2024-01-04,CUST01002,Laptop,Computers,1096.81,4.0,USA,NaN,5.0

In [36]:
#Rows with Payment_Method NaN value have rest of the data complete. 
#Its either system bug with registering data to database, or orders that were placed but not paid.

In [37]:
# DATA CLEANING PLAN
# ==================

# Fixing Order_Date (30 missing - 0.4%)?
# Delete them
# Reason: We don't know when the order was placed, it will be an issue during analysis

# Fixing Price null values(37 missing - 0.5%)?
# DROP these rows
# Reason: Without price we don't know how much the customer spent - this is critical

# Fixing Quantity null values(35 missing - 0.4%)?
# DROP these rows
# Reason: Quantity tells us if customer is wholesale or individual buyer
# It's only 0.4% of data so removing it won't hurt

# Fixing Payment_Method null values(1672 missing - 20%)?
# Replace with "Unknown"
# Reason: User needs to pay if the order was finalized, the method was not registered.
# FOR THIS PROJECT I WILL ASSUME THAT NaN VALUES ARE THE SYSTEM ERROR.

# Fixing Discount_Percent null values(1203 missing - 15%)?
# Replace with 0
# Reason:I assume No discount = 0% discount

# Fixing Duplicates (18 rows)?
# Delete them
# Reason: Impossible that someone ordered exactly same items at same second

In [38]:
df = df.dropna(subset =['Order_Date'])
df = df.dropna(subset =['Price'])
df = df.dropna(subset =['Quantity'])
df['Payment_Method'] = df['Payment_Method'].fillna('Unknown')
df['Discount_Percent'] = df['Discount_Percent'].fillna(0)
df = df.drop_duplicates(subset = ['Order_ID'])

In [39]:
df.nunique()

Order_ID            7898
Order_Date           365
Customer_ID          449
Product               10
Category               7
Price               6811
Quantity               4
Country                7
Payment_Method         5
Discount_Percent       4
dtype: int64

In [40]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Product             0
Category            0
Price               0
Quantity            0
Country             0
Payment_Method      0
Discount_Percent    0
dtype: int64

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
#Converting data trype
df=df.convert_dtypes()
df['Order_Date']= pd.to_datetime(df['Order_Date'])

In [43]:
df.to_csv('ecommerce_clean.csv', index=False)
print("Saved: ecommerce_clean.csv")

Saved: ecommerce_clean.csv

In [ ]:
#Creating segments

In [52]:
# Segment
orders = df.groupby('Customer_ID').size()
qty = df.groupby('Customer_ID')['Quantity'].sum()

segment = ((orders > 20) | (qty > 100)).map({True: 'STORE', False: 'INDIVIDUAL'})

lookup = pd.DataFrame({
    'Customer_ID': orders.index,
    'Segment': segment.values
})

lookup.to_csv('customer_segment_lookup.csv', index=False)

In [53]:
print(lookup)

    Customer_ID     Segment
0     CUST01001       STORE
1     CUST01002       STORE
2     CUST01003       STORE
3     CUST01004       STORE
4     CUST01005       STORE
..          ...         ...
444   CUST01974  INDIVIDUAL
445   CUST01977  INDIVIDUAL
446   CUST01982  INDIVIDUAL
447   CUST01984  INDIVIDUAL
448   CUST01994  INDIVIDUAL

[449 rows x 2 columns]